### ISSUE TITLE
Scouts

### ISSUE THREAD

**Issue by cloaked2222** [S5SS/dual-command#69]
#2.3->2.4
HW2 Scouts
Hiig Speed 512 **-> 486**
Vay Speed: 420/588 **-> 350/490** (upgrade)
Cost 300
Build Time 20
Sensors 9000/11000 **-> 7000/8550** (primary/secondary)

HW1 Scouts
Speed 490/613 **-> 486/608** (speed boost)
Cost 70
Build Time 8 **-> 7**
Sensors 8000/10000 **-> 7000/8500** (primary/secondary)

HW2 scouts can eventually get EMP, but other than that they are inferior to hw1 for their primary function of scouting. For 300ru, hw1 can have 4 scouts checking 4 different locations!

HW1 scouts also have the speed boost ability which grants a 25% speed bonus. Now that hw2 scout speeds have been nerfed in 2.4, hw1 scouts can more easily chase down and kill hw2 scouts - denying hw2 players scouting. Speed boost also allows hw1 scouts to outrun hw2 fighters, giving hw1 players far superior vision on the map. IMHO, this is a HUGE balance issue in the current 2.4 build.

Suggested changes:
HW2 Scouts: 200ru, 15sec (I should have done this in 2.3)
HW1 Scouts: Make speed boost +5%. Reduce sensors 1k. 
I believe all fighters/corvettes have an evasive bonus, so it makes no sense for scouts to not have one. Instead of the +10% that interceptors get, just make scouts only +5%.
I'd also like to point out that EMP is mainly useful when scouts are significantly faster than interceptors. Now that they're a bit slower than evasive ints, EMP bombs should probably have more range and faster delivery.

**Comment by S5SS** [comment]
A buff to emp range would be especially nice considering how they almost always emp themselves too. I think rather than making hw2 scouts cheaper, they should be the same as they are now but hw1 scouts should cost more instead since me and Fear want to make vision overall harder and more expensive to get - ATM in a dev branch they are 100 and 8s but I think even more would be needed to make HW1 players consider a probe instead.

**Comment by S5SS** [comment]
Build 11.1: Speed boost +25% => +10% (~30s speed boost time and ~2mins recharge meaning roughly 474 speed on average)
